import { FileText, Scale, Handshake, Heart, BookOpen, Gavel, ShoppingCart, ScrollText, Building2, Users, Briefcase, ClipboardList, Shield, Send, PenLine, FileCheck } from "lucide-react";

export type DocumentCategory = "litigation" | "contract" | "family" | "corporate";

export interface DocumentType {
  id: string;
  name: string;
  category: DocumentCategory;
  categoryLabel: string;
  description: string;
  icon: typeof FileText;
  fields: FormField[];
}

export interface FormField {
  name: string;
  label: string;
  type: "text" | "textarea" | "select";
  required: boolean;
  placeholder: string;
  options?: string[];
}

const partyFields = (prefix: string, label: string): FormField[] => [
  { name: `${prefix}Name`, label: `${label}姓名/名称`, type: "text", required: true, placeholder: `请输入${label}姓名或单位名称` },
  { name: `${prefix}IdNumber`, label: `${label}身份证号/统一社会信用代码`, type: "text", required: false, placeholder: "选填" },
  { name: `${prefix}Address`, label: `${label}住址`, type: "text", required: true, placeholder: `请输入${label}住址` },
  { name: `${prefix}Phone`, label: `${label}联系电话`, type: "text", required: false, placeholder: "选填" },
];

export const documentTypes: DocumentType[] = [
  {
    id: "civil-complaint",
    name: "民事起诉状",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "用于向法院提起民事诉讼，主张合法权益",
    icon: Scale,
    fields: [
      ...partyFields("plaintiff", "原告"),
      ...partyFields("defendant", "被告"),
      { name: "claims", label: "诉讼请求", type: "textarea", required: true, placeholder: "请逐条列明诉讼请求，如：1. 判令被告偿还借款本金XX元及利息；2. 本案诉讼费用由被告承担。" },
      { name: "factsAndReasons", label: "事实与理由", type: "textarea", required: true, placeholder: "请详细描述案件事实经过及起诉理由" },
      { name: "court", label: "管辖法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "evidence", label: "证据清单", type: "textarea", required: false, placeholder: "选填，如：1. 借条原件；2. 转账记录" },
    ],
  },
  {
    id: "defense-statement",
    name: "答辩状",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "被告针对原告起诉进行答辩和反驳",
    icon: FileText,
    fields: [
      ...partyFields("defendant", "答辩人(被告)"),
      ...partyFields("plaintiff", "被答辩人(原告)"),
      { name: "caseNumber", label: "案号", type: "text", required: false, placeholder: "如：(2024)京0105民初12345号" },
      { name: "defensePoints", label: "答辩意见", type: "textarea", required: true, placeholder: "请逐条列明答辩意见和事实依据" },
      { name: "evidence", label: "证据清单", type: "textarea", required: false, placeholder: "选填" },
    ],
  },
  {
    id: "property-preservation",
    name: "财产保全申请书",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "申请法院对被申请人财产采取保全措施",
    icon: Scale,
    fields: [
      ...partyFields("applicant", "申请人"),
      ...partyFields("respondent", "被申请人"),
      { name: "court", label: "申请法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "caseNumber", label: "案号（如已立案）", type: "text", required: false, placeholder: "选填" },
      { name: "preservationType", label: "保全类型", type: "select", required: true, placeholder: "", options: ["诉前财产保全", "诉中财产保全"] },
      { name: "preservationTarget", label: "保全标的", type: "textarea", required: true, placeholder: "请详细描述请求保全的财产，如：被申请人名下XX银行账户存款XX元" },
      { name: "preservationAmount", label: "保全金额（元）", type: "text", required: true, placeholder: "如：500000" },
      { name: "factsAndReasons", label: "事实与理由", type: "textarea", required: true, placeholder: "请说明申请保全的紧迫性和必要性" },
      { name: "guarantee", label: "担保说明", type: "textarea", required: true, placeholder: "请说明提供的担保方式及金额，如：以申请人名下XX房产提供担保" },
    ],
  },
  {
    id: "evidence-list",
    name: "证据清单/证据目录",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "整理案件证据材料的规范目录",
    icon: FileText,
    fields: [
      { name: "caseNumber", label: "案号", type: "text", required: false, placeholder: "选填" },
      { name: "partyName", label: "提交方名称", type: "text", required: true, placeholder: "请输入提交证据的当事人名称" },
      { name: "partyRole", label: "诉讼地位", type: "select", required: true, placeholder: "", options: ["原告", "被告", "第三人", "申请人", "被申请人"] },
      { name: "evidenceItems", label: "证据详情", type: "textarea", required: true, placeholder: "请逐条列明，格式如：\n1. 证据名称：借条原件\n   证明目的：证明借贷关系成立\n   来源：原告持有\n2. 证据名称：银行转账记录\n   证明目的：证明款项已交付\n   来源：XX银行出具" },
      { name: "court", label: "受理法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
    ],
  },
  {
    id: "power-of-attorney",
    name: "授权委托书（诉讼代理）",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "委托诉讼代理人参加诉讼的授权文书",
    icon: FileText,
    fields: [
      { name: "principalName", label: "委托人姓名/名称", type: "text", required: true, placeholder: "请输入委托人姓名或单位名称" },
      { name: "principalIdNumber", label: "身份证号/信用代码", type: "text", required: false, placeholder: "选填" },
      { name: "agentName", label: "受委托人姓名", type: "text", required: true, placeholder: "请输入代理人姓名" },
      { name: "agentUnit", label: "受委托人单位", type: "text", required: false, placeholder: "选填，如：XX律师事务所" },
      { name: "agentPhone", label: "受委托人联系电话", type: "text", required: false, placeholder: "选填" },
      { name: "caseDescription", label: "案件概述", type: "text", required: true, placeholder: "如：与XX买卖合同纠纷一案" },
      { name: "court", label: "受理法院", type: "text", required: false, placeholder: "选填" },
      { name: "authorityScope", label: "代理权限", type: "select", required: true, placeholder: "", options: ["一般授权代理", "特别授权代理（含代为承认、放弃、变更诉讼请求，进行和解，提起反诉或上诉等）"] },
      { name: "authorityPeriod", label: "委托期限", type: "text", required: false, placeholder: "选填，如：自签署之日起至本案终结" },
    ],
  },
  {
    id: "jurisdiction-objection",
    name: "管辖权异议申请书",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "对案件管辖法院提出异议的申请",
    icon: Gavel,
    fields: [
      ...partyFields("applicant", "申请人(被告)"),
      ...partyFields("respondent", "被申请人(原告)"),
      { name: "court", label: "受理法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "caseNumber", label: "案号", type: "text", required: true, placeholder: "如：(2024)京0105民初12345号" },
      { name: "objectionClaim", label: "异议请求", type: "textarea", required: true, placeholder: "如：请求将本案移送至XX人民法院管辖" },
      { name: "objectionReasons", label: "异议理由", type: "textarea", required: true, placeholder: "请详细阐述管辖不当的事实和法律依据" },
    ],
  },
  {
    id: "add-change-party",
    name: "追加/变更当事人申请书",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "申请追加或变更案件当事人",
    icon: FileText,
    fields: [
      { name: "applicantName", label: "申请人姓名/名称", type: "text", required: true, placeholder: "请输入申请人姓名" },
      { name: "court", label: "受理法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "caseNumber", label: "案号", type: "text", required: true, placeholder: "如：(2024)京0105民初12345号" },
      { name: "applicationType", label: "申请类型", type: "select", required: true, placeholder: "", options: ["追加被告", "追加第三人", "变更原告", "变更被告"] },
      { name: "targetPartyName", label: "拟追加/变更的当事人姓名", type: "text", required: true, placeholder: "请输入姓名或名称" },
      { name: "targetPartyAddress", label: "拟追加/变更当事人住址", type: "text", required: false, placeholder: "选填" },
      { name: "factsAndReasons", label: "事实与理由", type: "textarea", required: true, placeholder: "请详细说明追加或变更的事实和法律依据" },
    ],
  },
  {
    id: "withdrawal-application",
    name: "撤诉申请书",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "原告向法院申请撤回诉讼",
    icon: FileText,
    fields: [
      ...partyFields("plaintiff", "原告"),
      { name: "defendantName", label: "被告姓名/名称", type: "text", required: true, placeholder: "请输入被告姓名" },
      { name: "court", label: "受理法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "caseNumber", label: "案号", type: "text", required: true, placeholder: "如：(2024)京0105民初12345号" },
      { name: "withdrawalReason", label: "撤诉原因", type: "textarea", required: true, placeholder: "如：双方已自行和解，原告的诉讼目的已实现" },
    ],
  },
  {
    id: "extension-application",
    name: "延期举证/延期开庭申请书",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "申请延期提交证据或延期开庭审理",
    icon: FileText,
    fields: [
      { name: "applicantName", label: "申请人姓名/名称", type: "text", required: true, placeholder: "请输入申请人姓名" },
      { name: "applicantRole", label: "诉讼地位", type: "select", required: true, placeholder: "", options: ["原告", "被告", "第三人"] },
      { name: "court", label: "受理法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "caseNumber", label: "案号", type: "text", required: true, placeholder: "如：(2024)京0105民初12345号" },
      { name: "applicationType", label: "申请类型", type: "select", required: true, placeholder: "", options: ["延期举证", "延期开庭", "延期举证并延期开庭"] },
      { name: "extensionReason", label: "申请原因", type: "textarea", required: true, placeholder: "请详细说明需要延期的原因" },
      { name: "requestedDate", label: "申请延期至", type: "text", required: false, placeholder: "选填，如：2024年8月31日前" },
    ],
  },
  {
    id: "enforcement-application",
    name: "强制执行申请书",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "申请法院对生效判决/裁定进行强制执行",
    icon: Gavel,
    fields: [
      ...partyFields("applicant", "申请执行人"),
      ...partyFields("respondent", "被执行人"),
      { name: "court", label: "执行法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "legalBasis", label: "执行依据", type: "textarea", required: true, placeholder: "如：(2024)京0105民初12345号民事判决书" },
      { name: "enforcementClaims", label: "执行请求", type: "textarea", required: true, placeholder: "请逐条列明，如：1. 强制被执行人偿还XX元；2. 加倍支付延迟履行期间的债务利息" },
      { name: "executionClues", label: "被执行人财产线索", type: "textarea", required: true, placeholder: "请提供已知的被执行人财产线索，如：\n1. XX银行XX支行账户\n2. 名下位于XX的房产\n3. 名下XX牌汽车（车牌号XX）" },
      { name: "factsAndReasons", label: "事实与理由", type: "textarea", required: true, placeholder: "请说明被执行人未自动履行的情况" },
    ],
  },
  {
    id: "retrial-application",
    name: "再审申请书",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "对已生效判决申请再审的法律文书",
    icon: Gavel,
    fields: [
      ...partyFields("applicant", "再审申请人"),
      ...partyFields("respondent", "被申请人"),
      { name: "originalCourt", label: "原审法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "originalCaseNumber", label: "原审案号", type: "text", required: true, placeholder: "如：(2024)京0105民初12345号" },
      { name: "secondCourt", label: "二审法院（如有）", type: "text", required: false, placeholder: "选填" },
      { name: "secondCaseNumber", label: "二审案号（如有）", type: "text", required: false, placeholder: "选填" },
      { name: "retrialCourt", label: "再审法院", type: "text", required: true, placeholder: "如：北京市高级人民法院" },
      { name: "retrialClaims", label: "再审请求", type: "textarea", required: true, placeholder: "如：1. 撤销原判；2. 依法改判或发回重审" },
      { name: "retrialReasons", label: "再审事由", type: "textarea", required: true, placeholder: "请依据《民事诉讼法》第二百零七条列明再审事由" },
      { name: "factsAndReasons", label: "事实与理由", type: "textarea", required: true, placeholder: "请详细阐述支持再审的事实和法律依据" },
    ],
  },
  {
    id: "settlement-agreement",
    name: "和解协议（诉中/执行和解）",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "诉讼或执行过程中双方达成和解的协议",
    icon: Handshake,
    fields: [
      ...partyFields("partyA", "甲方"),
      ...partyFields("partyB", "乙方"),
      { name: "settlementStage", label: "和解阶段", type: "select", required: true, placeholder: "", options: ["诉中和解", "执行和解"] },
      { name: "court", label: "受理/执行法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "caseNumber", label: "案号", type: "text", required: true, placeholder: "如：(2024)京0105民初12345号" },
      { name: "settlementTerms", label: "和解内容", type: "textarea", required: true, placeholder: "请详细列明和解条款，如：乙方于XX日前支付甲方XX元，甲方放弃其余诉讼请求" },
      { name: "performanceDeadline", label: "履行期限", type: "text", required: true, placeholder: "如：本协议签订后30日内" },
      { name: "breachClause", label: "违约条款", type: "textarea", required: false, placeholder: "选填，如：一方违约，另一方有权申请恢复执行" },
      { name: "withdrawExecution", label: "是否同时撤回执行申请", type: "select", required: false, placeholder: "", options: ["是，履行完毕后撤回执行申请", "否"] },
    ],
  },
  {
    id: "loan-contract",
    name: "借款合同",
    category: "contract",
    categoryLabel: "合同类",
    description: "规范借贷双方的权利义务关系",
    icon: Handshake,
    fields: [
      ...partyFields("lender", "出借人(甲方)"),
      ...partyFields("borrower", "借款人(乙方)"),
      { name: "loanAmount", label: "借款金额（元）", type: "text", required: true, placeholder: "如：100000" },
      { name: "loanPurpose", label: "借款用途", type: "text", required: false, placeholder: "如：经营周转" },
      { name: "interestRate", label: "利率（年利率%）", type: "text", required: true, placeholder: "如：5" },
      { name: "loanTerm", label: "借款期限", type: "text", required: true, placeholder: "如：12个月，自2024年1月1日至2024年12月31日" },
      { name: "repaymentMethod", label: "还款方式", type: "select", required: true, placeholder: "", options: ["到期一次性还本付息", "按月付息到期还本", "等额本息", "等额本金"] },
      { name: "breachClause", label: "违约责任", type: "textarea", required: false, placeholder: "选填，如逾期利率、提前还款条款等" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向甲方所在地人民法院起诉", "协商解决，协商不成向乙方所在地人民法院起诉", "提交仲裁委员会仲裁"] },
    ],
  },
  {
    id: "rental-contract",
    name: "租赁合同",
    category: "contract",
    categoryLabel: "合同类",
    description: "明确出租方与承租方的租赁权利义务",
    icon: BookOpen,
    fields: [
      ...partyFields("lessor", "出租方(甲方)"),
      ...partyFields("lessee", "承租方(乙方)"),
      { name: "propertyAddress", label: "租赁物地址/描述", type: "text", required: true, placeholder: "如：北京市朝阳区XX路XX号XX室" },
      { name: "rentalTerm", label: "租赁期限", type: "text", required: true, placeholder: "如：2024年1月1日至2025年12月31日" },
      { name: "rent", label: "租金（元/月）", type: "text", required: true, placeholder: "如：5000" },
      { name: "paymentMethod", label: "付款方式", type: "select", required: true, placeholder: "", options: ["押一付一", "押一付三", "押二付一", "年付"] },
      { name: "deposit", label: "押金（元）", type: "text", required: false, placeholder: "如：5000" },
      { name: "specialTerms", label: "特殊约定", type: "textarea", required: false, placeholder: "选填，如装修、转租、维修责任等" },
    ],
  },
  {
    id: "divorce-agreement",
    name: "离婚协议书",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "协议离婚时明确双方权利义务的法律文书",
    icon: Heart,
    fields: [
      ...partyFields("male", "男方"),
      ...partyFields("female", "女方"),
      { name: "marriageDate", label: "结婚登记日期", type: "text", required: true, placeholder: "如：2018年6月1日" },
      { name: "marriagePlace", label: "结婚登记机关", type: "text", required: false, placeholder: "如：北京市朝阳区民政局" },
      { name: "divorceReason", label: "离婚原因", type: "select", required: true, placeholder: "", options: ["感情不和", "性格不合", "长期分居", "家庭暴力", "其他"] },
      { name: "children", label: "子女情况", type: "textarea", required: false, placeholder: "如：婚生子/女XXX，XXXX年X月X日出生，抚养权归XX方，另一方每月支付抚养费XX元" },
      { name: "property", label: "财产分配", type: "textarea", required: true, placeholder: "请详细列明共同财产的分配方案，如房产、存款、车辆等" },
      { name: "debt", label: "债务处理", type: "textarea", required: false, placeholder: "选填，如：双方确认无共同债务" },
    ],
  },
  {
    id: "appeal-statement",
    name: "上诉状",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "对一审判决不服，向上级法院提起上诉",
    icon: Gavel,
    fields: [
      ...partyFields("appellant", "上诉人"),
      ...partyFields("appellee", "被上诉人"),
      { name: "originalCourt", label: "原审法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "originalCaseNumber", label: "原审案号", type: "text", required: true, placeholder: "如：(2024)京0105民初12345号" },
      { name: "originalJudgment", label: "原审判决主要内容", type: "textarea", required: true, placeholder: "请简要描述一审判决的主要内容" },
      { name: "appealClaims", label: "上诉请求", type: "textarea", required: true, placeholder: "请逐条列明上诉请求，如：1. 撤销原判；2. 依法改判..." },
      { name: "appealReasons", label: "上诉理由", type: "textarea", required: true, placeholder: "请详细阐述上诉的事实和法律依据" },
      { name: "appellantCourt", label: "上诉法院", type: "text", required: true, placeholder: "如：北京市第三中级人民法院" },
    ],
  },
  {
    id: "sales-contract",
    name: "买卖合同",
    category: "contract",
    categoryLabel: "合同类",
    description: "规范买卖双方商品交易的权利义务",
    icon: ShoppingCart,
    fields: [
      ...partyFields("seller", "出卖方(甲方)"),
      ...partyFields("buyer", "买受方(乙方)"),
      { name: "goods", label: "标的物名称/规格", type: "textarea", required: true, placeholder: "请详细描述商品名称、规格、型号、数量等" },
      { name: "price", label: "价款（元）", type: "text", required: true, placeholder: "如：500000" },
      { name: "paymentMethod", label: "付款方式", type: "select", required: true, placeholder: "", options: ["一次性付清", "分期付款", "货到付款", "预付定金+尾款"] },
      { name: "deliveryMethod", label: "交付方式与地点", type: "text", required: true, placeholder: "如：甲方送货至乙方指定地点" },
      { name: "deliveryTime", label: "交付时间", type: "text", required: true, placeholder: "如：合同签订后30日内" },
      { name: "qualityStandard", label: "质量标准与验收", type: "textarea", required: false, placeholder: "选填，如：符合国家标准GB/T XXXX" },
      { name: "breachClause", label: "违约责任", type: "textarea", required: false, placeholder: "选填，如逾期交货违约金等" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向甲方所在地人民法院起诉", "协商解决，协商不成向乙方所在地人民法院起诉", "提交仲裁委员会仲裁"] },
    ],
  },
  {
    id: "labor-contract",
    name: "劳动合同",
    category: "contract",
    categoryLabel: "合同类",
    description: "规范用人单位与劳动者之间的劳动关系",
    icon: ClipboardList,
    fields: [
      ...partyFields("employer", "用人单位(甲方)"),
      ...partyFields("employee", "劳动者(乙方)"),
      { name: "contractType", label: "合同类型", type: "select", required: true, placeholder: "", options: ["固定期限劳动合同", "无固定期限劳动合同", "实习协议"] },
      { name: "contractTerm", label: "合同期限", type: "text", required: true, placeholder: "如：2024年1月1日至2026年12月31日" },
      { name: "probation", label: "试用期", type: "text", required: false, placeholder: "选填，如：3个月" },
      { name: "position", label: "工作岗位", type: "text", required: true, placeholder: "如：软件工程师" },
      { name: "workPlace", label: "工作地点", type: "text", required: true, placeholder: "如：北京市朝阳区" },
      { name: "workingHours", label: "工时制度", type: "select", required: true, placeholder: "", options: ["标准工时制", "综合计算工时制", "不定时工作制"] },
      { name: "salary", label: "劳动报酬（元/月）", type: "text", required: true, placeholder: "如：15000" },
      { name: "socialInsurance", label: "社会保险", type: "text", required: false, placeholder: "选填，默认按法定标准缴纳" },
      { name: "otherBenefits", label: "其他福利待遇", type: "textarea", required: false, placeholder: "选填，如年终奖、带薪假期等" },
    ],
  },
  {
    id: "labor-termination",
    name: "解除/终止劳动合同通知书",
    category: "contract",
    categoryLabel: "合同类",
    description: "用人单位或劳动者解除/终止劳动关系的正式通知",
    icon: FileCheck,
    fields: [
      ...partyFields("employer", "用人单位"),
      { name: "employeeName", label: "劳动者姓名", type: "text", required: true, placeholder: "请输入劳动者姓名" },
      { name: "employeeId", label: "劳动者身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "contractDate", label: "原劳动合同签订日期", type: "text", required: true, placeholder: "如：2022年1月1日" },
      { name: "terminationType", label: "解除/终止类型", type: "select", required: true, placeholder: "", options: ["协商一致解除", "用人单位单方解除", "劳动者单方解除", "合同到期终止"] },
      { name: "terminationDate", label: "解除/终止日期", type: "text", required: true, placeholder: "如：2024年6月30日" },
      { name: "terminationReason", label: "解除/终止原因", type: "textarea", required: true, placeholder: "请说明具体原因" },
      { name: "compensation", label: "经济补偿/赔偿", type: "textarea", required: false, placeholder: "选填，如：支付N+1个月工资经济补偿金" },
      { name: "handover", label: "工作交接要求", type: "textarea", required: false, placeholder: "选填" },
      { name: "includeProof", label: "是否同时出具离职证明", type: "select", required: true, placeholder: "", options: ["是，同时出具离职证明", "否，仅出具通知书"] },
    ],
  },
  {
    id: "nda",
    name: "保密协议（NDA）",
    category: "contract",
    categoryLabel: "合同类",
    description: "约定保密义务，保护商业秘密和机密信息",
    icon: Shield,
    fields: [
      ...partyFields("discloser", "披露方(甲方)"),
      ...partyFields("recipient", "接收方(乙方)"),
      { name: "confidentialScope", label: "保密信息范围", type: "textarea", required: true, placeholder: "请详细界定保密信息的范围，如：技术资料、客户名单、财务数据、商业计划等" },
      { name: "confidentialPeriod", label: "保密期限", type: "text", required: true, placeholder: "如：合同终止后2年内" },
      { name: "permittedUse", label: "许可使用范围", type: "textarea", required: false, placeholder: "选填，如：仅用于双方合作项目" },
      { name: "exclusions", label: "除外情形", type: "textarea", required: false, placeholder: "选填，如：公开信息、独立开发的信息等" },
      { name: "breachLiability", label: "违约责任", type: "textarea", required: true, placeholder: "如：违约方需赔偿损失，违约金XX元" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向甲方所在地人民法院起诉", "提交仲裁委员会仲裁"] },
    ],
  },
  {
    id: "non-compete",
    name: "竞业限制协议",
    category: "contract",
    categoryLabel: "合同类",
    description: "限制劳动者离职后的竞业行为并约定经济补偿",
    icon: Shield,
    fields: [
      ...partyFields("employer", "用人单位(甲方)"),
      ...partyFields("employee", "劳动者(乙方)"),
      { name: "restrictionScope", label: "竞业限制范围", type: "textarea", required: true, placeholder: "如：不得在同行业竞争企业任职、不得自行经营同类业务" },
      { name: "restrictionArea", label: "竞业限制地域", type: "text", required: true, placeholder: "如：中国大陆地区" },
      { name: "restrictionPeriod", label: "竞业限制期限", type: "text", required: true, placeholder: "如：离职后12个月（最长不超过2年）" },
      { name: "monthlyCompensation", label: "竞业限制补偿金（元/月）", type: "text", required: true, placeholder: "如：5000" },
      { name: "breachPenalty", label: "违约金", type: "text", required: true, placeholder: "如：100000元" },
      { name: "breachClause", label: "违约责任补充", type: "textarea", required: false, placeholder: "选填" },
    ],
  },
  {
    id: "service-contract",
    name: "委托服务合同",
    category: "contract",
    categoryLabel: "合同类",
    description: "适用于咨询、设计、开发、代运营等委托服务",
    icon: Handshake,
    fields: [
      ...partyFields("client", "委托方(甲方)"),
      ...partyFields("provider", "受托方(乙方)"),
      { name: "serviceType", label: "服务类型", type: "select", required: true, placeholder: "", options: ["咨询服务", "设计服务", "软件开发", "代运营服务", "其他"] },
      { name: "serviceContent", label: "服务内容与要求", type: "textarea", required: true, placeholder: "请详细描述服务内容、范围、标准和交付物" },
      { name: "serviceTerm", label: "服务期限", type: "text", required: true, placeholder: "如：2024年1月1日至2024年6月30日" },
      { name: "serviceFee", label: "服务费用（元）", type: "text", required: true, placeholder: "如：50000" },
      { name: "paymentMethod", label: "付款方式", type: "select", required: true, placeholder: "", options: ["一次性付清", "分期付款", "按月结算", "按里程碑付款"] },
      { name: "deliverables", label: "交付物与验收标准", type: "textarea", required: false, placeholder: "选填" },
      { name: "intellectualProperty", label: "知识产权归属", type: "select", required: true, placeholder: "", options: ["归委托方所有", "归受托方所有", "双方共有", "另行约定"] },
      { name: "breachClause", label: "违约责任", type: "textarea", required: false, placeholder: "选填" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向甲方所在地人民法院起诉", "提交仲裁委员会仲裁"] },
    ],
  },
  {
    id: "cooperation-agreement",
    name: "合作协议/框架协议",
    category: "contract",
    categoryLabel: "合同类",
    description: "约定合作方式、结算规则、违约及争议解决",
    icon: Handshake,
    fields: [
      ...partyFields("partyA", "甲方"),
      ...partyFields("partyB", "乙方"),
      { name: "cooperationContent", label: "合作内容", type: "textarea", required: true, placeholder: "请详细描述合作项目或业务内容" },
      { name: "cooperationTerm", label: "合作期限", type: "text", required: true, placeholder: "如：2024年1月1日至2025年12月31日" },
      { name: "rightsAndObligations", label: "双方权利义务", type: "textarea", required: true, placeholder: "请分别列明甲乙双方的主要权利和义务" },
      { name: "settlementMethod", label: "结算方式", type: "textarea", required: true, placeholder: "如：按月结算，次月15日前支付上月费用" },
      { name: "breachClause", label: "违约责任", type: "textarea", required: true, placeholder: "请约定违约情形及违约金/赔偿方式" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向甲方所在地人民法院起诉", "提交仲裁委员会仲裁"] },
      { name: "otherTerms", label: "其他约定", type: "textarea", required: false, placeholder: "选填，如保密条款、不可抗力等" },
    ],
  },
  {
    id: "equity-transfer",
    name: "股权转让协议",
    category: "contract",
    categoryLabel: "合同类",
    description: "明确股权转让双方的权利义务和交割安排",
    icon: ShoppingCart,
    fields: [
      ...partyFields("transferor", "转让方(甲方)"),
      ...partyFields("transferee", "受让方(乙方)"),
      { name: "targetCompany", label: "目标公司名称", type: "text", required: true, placeholder: "请输入目标公司全称" },
      { name: "equityRatio", label: "转让股权比例", type: "text", required: true, placeholder: "如：30%" },
      { name: "transferPrice", label: "转让价款（元）", type: "text", required: true, placeholder: "如：300000" },
      { name: "paymentMethod", label: "付款方式", type: "select", required: true, placeholder: "", options: ["一次性付清", "分期付款"] },
      { name: "paymentDeadline", label: "付款期限", type: "text", required: true, placeholder: "如：合同签订后30日内" },
      { name: "representations", label: "陈述与保证", type: "textarea", required: false, placeholder: "选填，如：甲方保证股权不存在质押、冻结等权利瑕疵" },
      { name: "breachClause", label: "违约责任", type: "textarea", required: false, placeholder: "选填" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向目标公司所在地人民法院起诉", "提交仲裁委员会仲裁"] },
    ],
  },
  {
    id: "property-supplement",
    name: "房屋买卖补充协议/居间服务协议",
    category: "contract",
    categoryLabel: "合同类",
    description: "房产交易补充条款或中介服务协议",
    icon: BookOpen,
    fields: [
      ...partyFields("partyA", "甲方"),
      ...partyFields("partyB", "乙方"),
      { name: "agreementType", label: "协议类型", type: "select", required: true, placeholder: "", options: ["房屋买卖补充协议", "居间服务协议（中介）"] },
      { name: "propertyAddress", label: "房屋地址", type: "text", required: true, placeholder: "如：北京市朝阳区XX路XX号XX室" },
      { name: "mainContractDate", label: "主合同签订日期", type: "text", required: false, placeholder: "选填，补充协议时填写" },
      { name: "supplementTerms", label: "补充/服务条款", type: "textarea", required: true, placeholder: "请详细列明补充条款或居间服务内容" },
      { name: "commissionFee", label: "佣金/服务费", type: "text", required: false, placeholder: "选填，如：成交价的2%" },
      { name: "breachClause", label: "违约责任", type: "textarea", required: false, placeholder: "选填" },
    ],
  },
  {
    id: "iou",
    name: "借条/欠条",
    category: "contract",
    categoryLabel: "合同类",
    description: "民间借贷常用的简易凭证，比借款合同更高频",
    icon: PenLine,
    fields: [
      { name: "iouType", label: "类型", type: "select", required: true, placeholder: "", options: ["借条", "欠条"] },
      { name: "borrowerName", label: "借款人/欠款人姓名", type: "text", required: true, placeholder: "请输入姓名" },
      { name: "borrowerIdNumber", label: "身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "lenderName", label: "出借人/债权人姓名", type: "text", required: true, placeholder: "请输入姓名" },
      { name: "amount", label: "金额（元）", type: "text", required: true, placeholder: "如：50000" },
      { name: "amountInWords", label: "大写金额", type: "text", required: false, placeholder: "如：伍万元整" },
      { name: "reason", label: "借款/欠款原因", type: "text", required: false, placeholder: "选填，如：因资金周转需要" },
      { name: "interestRate", label: "利率（年利率%）", type: "text", required: false, placeholder: "选填，如：5（不填则为无息）" },
      { name: "repaymentDate", label: "还款日期", type: "text", required: true, placeholder: "如：2025年6月30日前" },
      { name: "repaymentMethod", label: "还款方式", type: "select", required: false, placeholder: "", options: ["到期一次性还清", "分期还款", "随借随还"] },
    ],
  },
  {
    id: "repayment-plan",
    name: "还款计划/分期还款协议",
    category: "contract",
    categoryLabel: "合同类",
    description: "明确分期还款的金额、期限和违约责任",
    icon: FileText,
    fields: [
      ...partyFields("creditor", "债权人(甲方)"),
      ...partyFields("debtor", "债务人(乙方)"),
      { name: "totalDebt", label: "债务总额（元）", type: "text", required: true, placeholder: "如：100000" },
      { name: "debtOrigin", label: "债务来源", type: "text", required: true, placeholder: "如：2023年5月1日借款合同" },
      { name: "installments", label: "分期还款计划", type: "textarea", required: true, placeholder: "请逐期列明，如：\n第1期：2024年7月31日前还款10000元\n第2期：2024年8月31日前还款10000元" },
      { name: "breachClause", label: "逾期违约条款", type: "textarea", required: true, placeholder: "如：任一期逾期超过X日，剩余全部债务提前到期" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向甲方所在地人民法院起诉", "提交仲裁委员会仲裁"] },
    ],
  },
  {
    id: "demand-letter",
    name: "催款函/律师函（模板）",
    category: "contract",
    categoryLabel: "合同类",
    description: "催收欠款或主张权利的正式函件模板",
    icon: Send,
    fields: [
      { name: "letterType", label: "函件类型", type: "select", required: true, placeholder: "", options: ["催款函", "律师函（模板）"] },
      ...partyFields("sender", "发函方"),
      ...partyFields("recipient", "收函方"),
      { name: "debtAmount", label: "涉及金额（元）", type: "text", required: true, placeholder: "如：50000" },
      { name: "debtBasis", label: "债务依据", type: "textarea", required: true, placeholder: "请说明欠款依据，如合同编号、借条日期等" },
      { name: "factsDescription", label: "事实描述", type: "textarea", required: true, placeholder: "请简要描述欠款事实经过" },
      { name: "demands", label: "具体要求", type: "textarea", required: true, placeholder: "如：请于收函后7日内偿还全部欠款XX元" },
      { name: "legalConsequence", label: "法律后果警示", type: "textarea", required: false, placeholder: "选填，如：逾期未付将依法提起诉讼" },
    ],
  },
  {
    id: "will",
    name: "遗嘱",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "立遗嘱人对个人财产的身后安排",
    icon: ScrollText,
    fields: [
      { name: "testatorName", label: "立遗嘱人姓名", type: "text", required: true, placeholder: "请输入立遗嘱人姓名" },
      { name: "testatorIdNumber", label: "身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "testatorAddress", label: "住址", type: "text", required: true, placeholder: "请输入立遗嘱人住址" },
      { name: "willType", label: "遗嘱形式", type: "select", required: true, placeholder: "", options: ["自书遗嘱", "代书遗嘱", "打印遗嘱"] },
      { name: "mentalState", label: "精神状态说明", type: "text", required: true, placeholder: "如：本人精神状态良好，具有完全民事行为能力" },
      { name: "propertyList", label: "遗产清单", type: "textarea", required: true, placeholder: "请详细列明财产，如：1. 位于XX的房产一套；2. XX银行存款XX元" },
      { name: "distribution", label: "遗产分配方案", type: "textarea", required: true, placeholder: "请详细说明各项遗产的继承人及分配方式" },
      { name: "executor", label: "遗嘱执行人", type: "text", required: false, placeholder: "选填，指定遗嘱执行人姓名" },
      { name: "otherWishes", label: "其他遗愿", type: "textarea", required: false, placeholder: "选填，如丧葬安排等" },
    ],
  },
  {
    id: "separation-agreement",
    name: "分居协议",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "夫妻双方协议分居期间的权利义务安排",
    icon: FileText,
    fields: [
      ...partyFields("male", "男方"),
      ...partyFields("female", "女方"),
      { name: "marriageDate", label: "结婚登记日期", type: "text", required: true, placeholder: "如：2018年6月1日" },
      { name: "separationDate", label: "分居起始日期", type: "text", required: true, placeholder: "如：2024年1月1日" },
      { name: "separationReason", label: "分居原因", type: "select", required: true, placeholder: "", options: ["感情不和", "性格不合", "工作原因", "其他"] },
      { name: "livingArrangement", label: "居住安排", type: "textarea", required: true, placeholder: "请说明分居期间双方各自的居住地点" },
      { name: "childrenArrangement", label: "子女安排", type: "textarea", required: false, placeholder: "选填，分居期间子女的抚养与探望安排" },
      { name: "financialArrangement", label: "经济安排", type: "textarea", required: true, placeholder: "请说明分居期间的生活费用、债务承担等" },
      { name: "propertyArrangement", label: "财产约定", type: "textarea", required: false, placeholder: "选填，分居期间各自收入及财产归属约定" },
    ],
  },
  {
    id: "custody-agreement",
    name: "抚养权/探望权协议",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "明确子女抚养权归属及探望权行使方式",
    icon: Heart,
    fields: [
      ...partyFields("partyA", "甲方（父/母）"),
      ...partyFields("partyB", "乙方（父/母）"),
      { name: "childName", label: "子女姓名", type: "text", required: true, placeholder: "请输入子女姓名" },
      { name: "childBirthDate", label: "子女出生日期", type: "text", required: true, placeholder: "如：2020年5月1日" },
      { name: "custodyParty", label: "抚养权归属", type: "select", required: true, placeholder: "", options: ["归甲方", "归乙方", "轮流抚养"] },
      { name: "visitRights", label: "探望方式", type: "textarea", required: true, placeholder: "请详细说明探望时间、频率、接送方式等" },
      { name: "childSupport", label: "抚养费", type: "textarea", required: true, placeholder: "请说明金额、支付方式及期限，如：每月支付XX元至子女年满18周岁" },
      { name: "educationMedical", label: "教育医疗费用分担", type: "textarea", required: false, placeholder: "选填，如：大额教育及医疗费用由双方各承担50%" },
    ],
  },
  {
    id: "marital-property-agreement",
    name: "婚内财产协议",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "夫妻在婚姻关系存续期间对财产归属的约定",
    icon: Handshake,
    fields: [
      ...partyFields("husband", "丈夫"),
      ...partyFields("wife", "妻子"),
      { name: "marriageDate", label: "结婚登记日期", type: "text", required: true, placeholder: "如：2018年6月1日" },
      { name: "propertyList", label: "约定财产清单", type: "textarea", required: true, placeholder: "请详细列明涉及的财产，如房产、车辆、存款、股权等" },
      { name: "ownershipArrangement", label: "财产归属约定", type: "textarea", required: true, placeholder: "请说明各项财产的归属方式（共同所有/各自所有/按比例）" },
      { name: "incomeArrangement", label: "收入归属约定", type: "textarea", required: false, placeholder: "选填，如：婚后各自工资收入归各自所有" },
      { name: "debtArrangement", label: "债务承担约定", type: "textarea", required: false, placeholder: "选填，如：各自名下债务由各自承担" },
    ],
  },
  {
    id: "will-amendment",
    name: "遗嘱补充/变更/撤销声明",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "对已有遗嘱进行补充、修改或撤销",
    icon: ScrollText,
    fields: [
      { name: "testatorName", label: "立遗嘱人姓名", type: "text", required: true, placeholder: "请输入姓名" },
      { name: "testatorIdNumber", label: "身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "testatorAddress", label: "住址", type: "text", required: true, placeholder: "请输入住址" },
      { name: "actionType", label: "操作类型", type: "select", required: true, placeholder: "", options: ["补充遗嘱", "变更遗嘱", "撤销遗嘱"] },
      { name: "originalWillDate", label: "原遗嘱订立日期", type: "text", required: true, placeholder: "如：2022年3月15日" },
      { name: "originalWillSummary", label: "原遗嘱主要内容概述", type: "textarea", required: true, placeholder: "请简要描述原遗嘱的主要内容" },
      { name: "changes", label: "补充/变更/撤销内容", type: "textarea", required: true, placeholder: "请详细说明本次补充、变更或撤销的具体内容" },
      { name: "mentalState", label: "精神状态说明", type: "text", required: true, placeholder: "如：本人精神状态良好，具有完全民事行为能力" },
    ],
  },
  {
    id: "inheritance-waiver",
    name: "放弃继承权声明书",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "继承人自愿放弃继承遗产权利的声明",
    icon: ScrollText,
    fields: [
      { name: "declarantName", label: "声明人姓名", type: "text", required: true, placeholder: "请输入声明人姓名" },
      { name: "declarantIdNumber", label: "身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "declarantAddress", label: "住址", type: "text", required: true, placeholder: "请输入住址" },
      { name: "deceasedName", label: "被继承人姓名", type: "text", required: true, placeholder: "请输入被继承人姓名" },
      { name: "relationship", label: "与被继承人关系", type: "select", required: true, placeholder: "", options: ["配偶", "子女", "父母", "兄弟姐妹", "其他"] },
      { name: "deathDate", label: "被继承人去世日期", type: "text", required: true, placeholder: "如：2024年1月1日" },
      { name: "estateDescription", label: "涉及遗产描述", type: "textarea", required: true, placeholder: "请简要描述放弃继承的遗产内容" },
      { name: "waiverReason", label: "放弃原因", type: "textarea", required: false, placeholder: "选填，如：自愿放弃，无任何胁迫" },
    ],
  },
  {
    id: "inheritance-partition",
    name: "继承分割协议",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "全体继承人协商确定遗产分割方案",
    icon: Handshake,
    fields: [
      { name: "deceasedName", label: "被继承人姓名", type: "text", required: true, placeholder: "请输入被继承人姓名" },
      { name: "deathDate", label: "去世日期", type: "text", required: true, placeholder: "如：2024年1月1日" },
      { name: "heirs", label: "全体继承人信息", type: "textarea", required: true, placeholder: "请列明所有继承人姓名、身份证号、与被继承人关系" },
      { name: "estateList", label: "遗产清单", type: "textarea", required: true, placeholder: "请详细列明全部遗产，如房产、存款、车辆、股权等" },
      { name: "partitionPlan", label: "分割方案", type: "textarea", required: true, placeholder: "请详细说明各项遗产的分配方式及归属" },
      { name: "debtHandling", label: "债务处理", type: "textarea", required: false, placeholder: "选填，如：被继承人债务由XX承担" },
      { name: "otherTerms", label: "其他约定", type: "textarea", required: false, placeholder: "选填" },
    ],
  },
  {
    id: "guardianship-agreement",
    name: "监护协议/指定监护人声明",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "指定或协商确定被监护人的监护人及责任",
    icon: Heart,
    fields: [
      { name: "wardName", label: "被监护人姓名", type: "text", required: true, placeholder: "请输入被监护人姓名" },
      { name: "wardIdNumber", label: "被监护人身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "wardSituation", label: "被监护人情况", type: "select", required: true, placeholder: "", options: ["未成年人", "无民事行为能力人", "限制民事行为能力人"] },
      ...partyFields("guardian", "监护人"),
      { name: "guardianRelationship", label: "与被监护人关系", type: "select", required: true, placeholder: "", options: ["父母", "祖父母/外祖父母", "兄姐", "其他近亲属", "其他"] },
      { name: "guardianshipScope", label: "监护职责范围", type: "textarea", required: true, placeholder: "请说明监护职责，如人身照顾、财产管理、教育医疗决定等" },
      { name: "guardianshipTerm", label: "监护期限", type: "text", required: false, placeholder: "选填，如：至被监护人年满18周岁" },
      { name: "financialArrangement", label: "费用安排", type: "textarea", required: false, placeholder: "选填，如：被监护人财产用于其生活、教育、医疗等" },
    ],
  },
  {
    id: "shareholder-resolution",
    name: "股东会决议/董事会决议",
    category: "corporate",
    categoryLabel: "商事/公司治理类",
    description: "记录股东会或董事会决议事项的正式文书",
    icon: Building2,
    fields: [
      { name: "companyName", label: "公司名称", type: "text", required: true, placeholder: "请输入公司全称" },
      { name: "creditCode", label: "统一社会信用代码", type: "text", required: false, placeholder: "选填" },
      { name: "meetingType", label: "会议类型", type: "select", required: true, placeholder: "", options: ["股东会决议", "董事会决议"] },
      { name: "meetingDate", label: "会议日期", type: "text", required: true, placeholder: "如：2024年6月1日" },
      { name: "meetingPlace", label: "会议地点", type: "text", required: false, placeholder: "选填" },
      { name: "attendees", label: "出席人员", type: "textarea", required: true, placeholder: "请列明全体出席股东/董事及其持股比例或职务" },
      { name: "resolutions", label: "决议事项", type: "textarea", required: true, placeholder: "请逐条列明决议内容，如：1. 同意变更法定代表人为XXX；2. 同意修改公司章程第X条..." },
      { name: "votingResult", label: "表决结果", type: "textarea", required: true, placeholder: "如：全体股东一致同意/经代表XX%表决权的股东同意通过" },
    ],
  },
  {
    id: "legal-rep-change",
    name: "法定代表人变更文件",
    category: "corporate",
    categoryLabel: "商事/公司治理类",
    description: "法定代表人变更的决议及申请文件",
    icon: Briefcase,
    fields: [
      { name: "companyName", label: "公司名称", type: "text", required: true, placeholder: "请输入公司全称" },
      { name: "creditCode", label: "统一社会信用代码", type: "text", required: false, placeholder: "选填" },
      { name: "originalRep", label: "原法定代表人姓名", type: "text", required: true, placeholder: "请输入原法定代表人姓名" },
      { name: "originalRepId", label: "原法定代表人身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "newRep", label: "新法定代表人姓名", type: "text", required: true, placeholder: "请输入新法定代表人姓名" },
      { name: "newRepId", label: "新法定代表人身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "changeReason", label: "变更原因", type: "textarea", required: true, placeholder: "如：原法定代表人因个人原因辞去职务" },
      { name: "changeDate", label: "变更日期", type: "text", required: true, placeholder: "如：2024年6月1日" },
      { name: "registrationAuthority", label: "登记机关", type: "text", required: false, placeholder: "选填，如：北京市朝阳区市场监督管理局" },
    ],
  },
  {
    id: "company-articles",
    name: "公司章程（简版）",
    category: "corporate",
    categoryLabel: "商事/公司治理类",
    description: "有限责任公司章程简版模板",
    icon: BookOpen,
    fields: [
      { name: "companyName", label: "公司名称", type: "text", required: true, placeholder: "请输入公司全称" },
      { name: "registeredAddress", label: "注册地址", type: "text", required: true, placeholder: "请输入公司注册地址" },
      { name: "businessScope", label: "经营范围", type: "textarea", required: true, placeholder: "请描述主要经营范围" },
      { name: "registeredCapital", label: "注册资本（万元）", type: "text", required: true, placeholder: "如：100" },
      { name: "shareholders", label: "股东及出资信息", type: "textarea", required: true, placeholder: "请列明各股东姓名/名称、出资额、出资比例、出资方式、出资时间" },
      { name: "legalRep", label: "法定代表人", type: "text", required: true, placeholder: "请输入法定代表人姓名" },
      { name: "executiveDirector", label: "执行董事/董事会", type: "select", required: true, placeholder: "", options: ["设执行董事（不设董事会）", "设董事会"] },
      { name: "supervisor", label: "监事/监事会", type: "select", required: true, placeholder: "", options: ["设监事一名（不设监事会）", "设监事会"] },
      { name: "profitDistribution", label: "利润分配方式", type: "select", required: true, placeholder: "", options: ["按出资比例分配", "按章程约定比例分配"] },
    ],
  },
  {
    id: "equity-holding-agreement",
    name: "股权代持协议",
    category: "corporate",
    categoryLabel: "商事/公司治理类",
    description: "明确实际出资人与名义股东的权利义务（含风险提示）",
    icon: Users,
    fields: [
      ...partyFields("actualHolder", "实际出资人(甲方)"),
      ...partyFields("nominalHolder", "名义股东(乙方)"),
      { name: "targetCompany", label: "目标公司名称", type: "text", required: true, placeholder: "请输入被代持股权的公司全称" },
      { name: "equityAmount", label: "代持股权比例/金额", type: "text", required: true, placeholder: "如：30%股权，对应出资额30万元" },
      { name: "investmentAmount", label: "实际出资金额（元）", type: "text", required: true, placeholder: "如：300000" },
      { name: "rightsExercise", label: "股东权利行使方式", type: "textarea", required: true, placeholder: "请说明表决权、分红权等如何行使，如：乙方须按甲方书面指示行使表决权" },
      { name: "profitDistribution", label: "收益分配约定", type: "textarea", required: true, placeholder: "如：乙方收到分红后X日内全额转付甲方" },
      { name: "transferRestriction", label: "股权处分限制", type: "textarea", required: true, placeholder: "如：未经甲方书面同意，乙方不得转让、质押或以其他方式处分代持股权" },
      { name: "breachClause", label: "违约责任", type: "textarea", required: true, placeholder: "请约定违约金或赔偿方式" },
      { name: "riskWarning", label: "风险提示事项", type: "textarea", required: false, placeholder: "选填，如：代持协议不得对抗善意第三人；名义股东被执行时的风险等" },
    ],
  },
  {
    id: "partnership-agreement",
    name: "合伙协议",
    category: "corporate",
    categoryLabel: "商事/公司治理类",
    description: "合伙企业或项目合伙的权利义务约定",
    icon: Handshake,
    fields: [
      { name: "partnershipName", label: "合伙企业/项目名称", type: "text", required: true, placeholder: "请输入合伙企业或项目名称" },
      { name: "partnershipType", label: "合伙类型", type: "select", required: true, placeholder: "", options: ["普通合伙", "有限合伙", "项目合伙（非企业）"] },
      { name: "partners", label: "全体合伙人信息", type: "textarea", required: true, placeholder: "请列明各合伙人姓名/名称、身份证号/信用代码、出资额、出资方式" },
      { name: "totalCapital", label: "出资总额（元）", type: "text", required: true, placeholder: "如：500000" },
      { name: "businessScope", label: "经营范围/合伙事务", type: "textarea", required: true, placeholder: "请描述合伙经营的业务范围或项目内容" },
      { name: "profitSharing", label: "利润分配与亏损分担", type: "textarea", required: true, placeholder: "请说明利润分配比例及亏损承担方式" },
      { name: "executingPartner", label: "执行事务合伙人", type: "text", required: true, placeholder: "请指定执行事务的合伙人姓名" },
      { name: "decisionMaking", label: "决策机制", type: "textarea", required: false, placeholder: "选填，如：重大事项须全体合伙人一致同意" },
      { name: "withdrawalTerms", label: "入伙与退伙条款", type: "textarea", required: false, placeholder: "选填，如：退伙需提前30日书面通知" },
      { name: "dissolution", label: "解散与清算", type: "textarea", required: false, placeholder: "选填，如：合伙期满或全体合伙人一致同意解散" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向合伙企业所在地人民法院起诉", "提交仲裁委员会仲裁"] },
    ],
  },
];

export const categories = [
  { id: "litigation" as DocumentCategory, label: "诉讼类", description: "起诉状、答辩状、上诉状等" },
  { id: "contract" as DocumentCategory, label: "合同类", description: "借款、租赁、买卖等合同" },
  { id: "family" as DocumentCategory, label: "身份/家事类", description: "离婚协议、遗嘱等" },
  { id: "corporate" as DocumentCategory, label: "商事/公司治理类", description: "股东会决议、章程、合伙协议等" },
];
