import { FileText, Scale, Handshake, Heart, BookOpen, Gavel, ShoppingCart, ScrollText, Building2, Users, Briefcase } from "lucide-react";

export type DocumentCategory = "litigation" | "contract" | "family" | "corporate";

export interface DocumentType {
  id: string;
  name: string;
  category: DocumentCategory;
  categoryLabel: string;
  description: string;
  icon: typeof FileText;
  fields: FormField[];
}

export interface FormField {
  name: string;
  label: string;
  type: "text" | "textarea" | "select";
  required: boolean;
  placeholder: string;
  options?: string[];
}

const partyFields = (prefix: string, label: string): FormField[] => [
  { name: `${prefix}Name`, label: `${label}姓名/名称`, type: "text", required: true, placeholder: `请输入${label}姓名或单位名称` },
  { name: `${prefix}IdNumber`, label: `${label}身份证号/统一社会信用代码`, type: "text", required: false, placeholder: "选填" },
  { name: `${prefix}Address`, label: `${label}住址`, type: "text", required: true, placeholder: `请输入${label}住址` },
  { name: `${prefix}Phone`, label: `${label}联系电话`, type: "text", required: false, placeholder: "选填" },
];

export const documentTypes: DocumentType[] = [
  {
    id: "civil-complaint",
    name: "民事起诉状",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "用于向法院提起民事诉讼，主张合法权益",
    icon: Scale,
    fields: [
      ...partyFields("plaintiff", "原告"),
      ...partyFields("defendant", "被告"),
      { name: "claims", label: "诉讼请求", type: "textarea", required: true, placeholder: "请逐条列明诉讼请求，如：1. 判令被告偿还借款本金XX元及利息；2. 本案诉讼费用由被告承担。" },
      { name: "factsAndReasons", label: "事实与理由", type: "textarea", required: true, placeholder: "请详细描述案件事实经过及起诉理由" },
      { name: "court", label: "管辖法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "evidence", label: "证据清单", type: "textarea", required: false, placeholder: "选填，如：1. 借条原件；2. 转账记录" },
    ],
  },
  {
    id: "defense-statement",
    name: "答辩状",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "被告针对原告起诉进行答辩和反驳",
    icon: FileText,
    fields: [
      ...partyFields("defendant", "答辩人(被告)"),
      ...partyFields("plaintiff", "被答辩人(原告)"),
      { name: "caseNumber", label: "案号", type: "text", required: false, placeholder: "如：(2024)京0105民初12345号" },
      { name: "defensePoints", label: "答辩意见", type: "textarea", required: true, placeholder: "请逐条列明答辩意见和事实依据" },
      { name: "evidence", label: "证据清单", type: "textarea", required: false, placeholder: "选填" },
    ],
  },
  {
    id: "loan-contract",
    name: "借款合同",
    category: "contract",
    categoryLabel: "合同类",
    description: "规范借贷双方的权利义务关系",
    icon: Handshake,
    fields: [
      ...partyFields("lender", "出借人(甲方)"),
      ...partyFields("borrower", "借款人(乙方)"),
      { name: "loanAmount", label: "借款金额（元）", type: "text", required: true, placeholder: "如：100000" },
      { name: "loanPurpose", label: "借款用途", type: "text", required: false, placeholder: "如：经营周转" },
      { name: "interestRate", label: "利率（年利率%）", type: "text", required: true, placeholder: "如：5" },
      { name: "loanTerm", label: "借款期限", type: "text", required: true, placeholder: "如：12个月，自2024年1月1日至2024年12月31日" },
      { name: "repaymentMethod", label: "还款方式", type: "select", required: true, placeholder: "", options: ["到期一次性还本付息", "按月付息到期还本", "等额本息", "等额本金"] },
      { name: "breachClause", label: "违约责任", type: "textarea", required: false, placeholder: "选填，如逾期利率、提前还款条款等" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向甲方所在地人民法院起诉", "协商解决，协商不成向乙方所在地人民法院起诉", "提交仲裁委员会仲裁"] },
    ],
  },
  {
    id: "rental-contract",
    name: "租赁合同",
    category: "contract",
    categoryLabel: "合同类",
    description: "明确出租方与承租方的租赁权利义务",
    icon: BookOpen,
    fields: [
      ...partyFields("lessor", "出租方(甲方)"),
      ...partyFields("lessee", "承租方(乙方)"),
      { name: "propertyAddress", label: "租赁物地址/描述", type: "text", required: true, placeholder: "如：北京市朝阳区XX路XX号XX室" },
      { name: "rentalTerm", label: "租赁期限", type: "text", required: true, placeholder: "如：2024年1月1日至2025年12月31日" },
      { name: "rent", label: "租金（元/月）", type: "text", required: true, placeholder: "如：5000" },
      { name: "paymentMethod", label: "付款方式", type: "select", required: true, placeholder: "", options: ["押一付一", "押一付三", "押二付一", "年付"] },
      { name: "deposit", label: "押金（元）", type: "text", required: false, placeholder: "如：5000" },
      { name: "specialTerms", label: "特殊约定", type: "textarea", required: false, placeholder: "选填，如装修、转租、维修责任等" },
    ],
  },
  {
    id: "divorce-agreement",
    name: "离婚协议书",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "协议离婚时明确双方权利义务的法律文书",
    icon: Heart,
    fields: [
      ...partyFields("male", "男方"),
      ...partyFields("female", "女方"),
      { name: "marriageDate", label: "结婚登记日期", type: "text", required: true, placeholder: "如：2018年6月1日" },
      { name: "marriagePlace", label: "结婚登记机关", type: "text", required: false, placeholder: "如：北京市朝阳区民政局" },
      { name: "divorceReason", label: "离婚原因", type: "select", required: true, placeholder: "", options: ["感情不和", "性格不合", "长期分居", "家庭暴力", "其他"] },
      { name: "children", label: "子女情况", type: "textarea", required: false, placeholder: "如：婚生子/女XXX，XXXX年X月X日出生，抚养权归XX方，另一方每月支付抚养费XX元" },
      { name: "property", label: "财产分配", type: "textarea", required: true, placeholder: "请详细列明共同财产的分配方案，如房产、存款、车辆等" },
      { name: "debt", label: "债务处理", type: "textarea", required: false, placeholder: "选填，如：双方确认无共同债务" },
    ],
  },
  {
    id: "appeal-statement",
    name: "上诉状",
    category: "litigation",
    categoryLabel: "诉讼类",
    description: "对一审判决不服，向上级法院提起上诉",
    icon: Gavel,
    fields: [
      ...partyFields("appellant", "上诉人"),
      ...partyFields("appellee", "被上诉人"),
      { name: "originalCourt", label: "原审法院", type: "text", required: true, placeholder: "如：北京市朝阳区人民法院" },
      { name: "originalCaseNumber", label: "原审案号", type: "text", required: true, placeholder: "如：(2024)京0105民初12345号" },
      { name: "originalJudgment", label: "原审判决主要内容", type: "textarea", required: true, placeholder: "请简要描述一审判决的主要内容" },
      { name: "appealClaims", label: "上诉请求", type: "textarea", required: true, placeholder: "请逐条列明上诉请求，如：1. 撤销原判；2. 依法改判..." },
      { name: "appealReasons", label: "上诉理由", type: "textarea", required: true, placeholder: "请详细阐述上诉的事实和法律依据" },
      { name: "appellantCourt", label: "上诉法院", type: "text", required: true, placeholder: "如：北京市第三中级人民法院" },
    ],
  },
  {
    id: "sales-contract",
    name: "买卖合同",
    category: "contract",
    categoryLabel: "合同类",
    description: "规范买卖双方商品交易的权利义务",
    icon: ShoppingCart,
    fields: [
      ...partyFields("seller", "出卖方(甲方)"),
      ...partyFields("buyer", "买受方(乙方)"),
      { name: "goods", label: "标的物名称/规格", type: "textarea", required: true, placeholder: "请详细描述商品名称、规格、型号、数量等" },
      { name: "price", label: "价款（元）", type: "text", required: true, placeholder: "如：500000" },
      { name: "paymentMethod", label: "付款方式", type: "select", required: true, placeholder: "", options: ["一次性付清", "分期付款", "货到付款", "预付定金+尾款"] },
      { name: "deliveryMethod", label: "交付方式与地点", type: "text", required: true, placeholder: "如：甲方送货至乙方指定地点" },
      { name: "deliveryTime", label: "交付时间", type: "text", required: true, placeholder: "如：合同签订后30日内" },
      { name: "qualityStandard", label: "质量标准与验收", type: "textarea", required: false, placeholder: "选填，如：符合国家标准GB/T XXXX" },
      { name: "breachClause", label: "违约责任", type: "textarea", required: false, placeholder: "选填，如逾期交货违约金等" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向甲方所在地人民法院起诉", "协商解决，协商不成向乙方所在地人民法院起诉", "提交仲裁委员会仲裁"] },
    ],
  },
  {
    id: "will",
    name: "遗嘱",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "立遗嘱人对个人财产的身后安排",
    icon: ScrollText,
    fields: [
      { name: "testatorName", label: "立遗嘱人姓名", type: "text", required: true, placeholder: "请输入立遗嘱人姓名" },
      { name: "testatorIdNumber", label: "身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "testatorAddress", label: "住址", type: "text", required: true, placeholder: "请输入立遗嘱人住址" },
      { name: "willType", label: "遗嘱形式", type: "select", required: true, placeholder: "", options: ["自书遗嘱", "代书遗嘱", "打印遗嘱"] },
      { name: "mentalState", label: "精神状态说明", type: "text", required: true, placeholder: "如：本人精神状态良好，具有完全民事行为能力" },
      { name: "propertyList", label: "遗产清单", type: "textarea", required: true, placeholder: "请详细列明财产，如：1. 位于XX的房产一套；2. XX银行存款XX元" },
      { name: "distribution", label: "遗产分配方案", type: "textarea", required: true, placeholder: "请详细说明各项遗产的继承人及分配方式" },
      { name: "executor", label: "遗嘱执行人", type: "text", required: false, placeholder: "选填，指定遗嘱执行人姓名" },
      { name: "otherWishes", label: "其他遗愿", type: "textarea", required: false, placeholder: "选填，如丧葬安排等" },
    ],
  },
  {
    id: "separation-agreement",
    name: "分居协议",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "夫妻双方协议分居期间的权利义务安排",
    icon: FileText,
    fields: [
      ...partyFields("male", "男方"),
      ...partyFields("female", "女方"),
      { name: "marriageDate", label: "结婚登记日期", type: "text", required: true, placeholder: "如：2018年6月1日" },
      { name: "separationDate", label: "分居起始日期", type: "text", required: true, placeholder: "如：2024年1月1日" },
      { name: "separationReason", label: "分居原因", type: "select", required: true, placeholder: "", options: ["感情不和", "性格不合", "工作原因", "其他"] },
      { name: "livingArrangement", label: "居住安排", type: "textarea", required: true, placeholder: "请说明分居期间双方各自的居住地点" },
      { name: "childrenArrangement", label: "子女安排", type: "textarea", required: false, placeholder: "选填，分居期间子女的抚养与探望安排" },
      { name: "financialArrangement", label: "经济安排", type: "textarea", required: true, placeholder: "请说明分居期间的生活费用、债务承担等" },
      { name: "propertyArrangement", label: "财产约定", type: "textarea", required: false, placeholder: "选填，分居期间各自收入及财产归属约定" },
    ],
  },
  {
    id: "custody-agreement",
    name: "抚养权/探望权协议",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "明确子女抚养权归属及探望权行使方式",
    icon: Heart,
    fields: [
      ...partyFields("partyA", "甲方（父/母）"),
      ...partyFields("partyB", "乙方（父/母）"),
      { name: "childName", label: "子女姓名", type: "text", required: true, placeholder: "请输入子女姓名" },
      { name: "childBirthDate", label: "子女出生日期", type: "text", required: true, placeholder: "如：2020年5月1日" },
      { name: "custodyParty", label: "抚养权归属", type: "select", required: true, placeholder: "", options: ["归甲方", "归乙方", "轮流抚养"] },
      { name: "visitRights", label: "探望方式", type: "textarea", required: true, placeholder: "请详细说明探望时间、频率、接送方式等" },
      { name: "childSupport", label: "抚养费", type: "textarea", required: true, placeholder: "请说明金额、支付方式及期限，如：每月支付XX元至子女年满18周岁" },
      { name: "educationMedical", label: "教育医疗费用分担", type: "textarea", required: false, placeholder: "选填，如：大额教育及医疗费用由双方各承担50%" },
    ],
  },
  {
    id: "marital-property-agreement",
    name: "婚内财产协议",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "夫妻在婚姻关系存续期间对财产归属的约定",
    icon: Handshake,
    fields: [
      ...partyFields("husband", "丈夫"),
      ...partyFields("wife", "妻子"),
      { name: "marriageDate", label: "结婚登记日期", type: "text", required: true, placeholder: "如：2018年6月1日" },
      { name: "propertyList", label: "约定财产清单", type: "textarea", required: true, placeholder: "请详细列明涉及的财产，如房产、车辆、存款、股权等" },
      { name: "ownershipArrangement", label: "财产归属约定", type: "textarea", required: true, placeholder: "请说明各项财产的归属方式（共同所有/各自所有/按比例）" },
      { name: "incomeArrangement", label: "收入归属约定", type: "textarea", required: false, placeholder: "选填，如：婚后各自工资收入归各自所有" },
      { name: "debtArrangement", label: "债务承担约定", type: "textarea", required: false, placeholder: "选填，如：各自名下债务由各自承担" },
    ],
  },
  {
    id: "will-amendment",
    name: "遗嘱补充/变更/撤销声明",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "对已有遗嘱进行补充、修改或撤销",
    icon: ScrollText,
    fields: [
      { name: "testatorName", label: "立遗嘱人姓名", type: "text", required: true, placeholder: "请输入姓名" },
      { name: "testatorIdNumber", label: "身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "testatorAddress", label: "住址", type: "text", required: true, placeholder: "请输入住址" },
      { name: "actionType", label: "操作类型", type: "select", required: true, placeholder: "", options: ["补充遗嘱", "变更遗嘱", "撤销遗嘱"] },
      { name: "originalWillDate", label: "原遗嘱订立日期", type: "text", required: true, placeholder: "如：2022年3月15日" },
      { name: "originalWillSummary", label: "原遗嘱主要内容概述", type: "textarea", required: true, placeholder: "请简要描述原遗嘱的主要内容" },
      { name: "changes", label: "补充/变更/撤销内容", type: "textarea", required: true, placeholder: "请详细说明本次补充、变更或撤销的具体内容" },
      { name: "mentalState", label: "精神状态说明", type: "text", required: true, placeholder: "如：本人精神状态良好，具有完全民事行为能力" },
    ],
  },
  {
    id: "inheritance-waiver",
    name: "放弃继承权声明书",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "继承人自愿放弃继承遗产权利的声明",
    icon: ScrollText,
    fields: [
      { name: "declarantName", label: "声明人姓名", type: "text", required: true, placeholder: "请输入声明人姓名" },
      { name: "declarantIdNumber", label: "身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "declarantAddress", label: "住址", type: "text", required: true, placeholder: "请输入住址" },
      { name: "deceasedName", label: "被继承人姓名", type: "text", required: true, placeholder: "请输入被继承人姓名" },
      { name: "relationship", label: "与被继承人关系", type: "select", required: true, placeholder: "", options: ["配偶", "子女", "父母", "兄弟姐妹", "其他"] },
      { name: "deathDate", label: "被继承人去世日期", type: "text", required: true, placeholder: "如：2024年1月1日" },
      { name: "estateDescription", label: "涉及遗产描述", type: "textarea", required: true, placeholder: "请简要描述放弃继承的遗产内容" },
      { name: "waiverReason", label: "放弃原因", type: "textarea", required: false, placeholder: "选填，如：自愿放弃，无任何胁迫" },
    ],
  },
  {
    id: "inheritance-partition",
    name: "继承分割协议",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "全体继承人协商确定遗产分割方案",
    icon: Handshake,
    fields: [
      { name: "deceasedName", label: "被继承人姓名", type: "text", required: true, placeholder: "请输入被继承人姓名" },
      { name: "deathDate", label: "去世日期", type: "text", required: true, placeholder: "如：2024年1月1日" },
      { name: "heirs", label: "全体继承人信息", type: "textarea", required: true, placeholder: "请列明所有继承人姓名、身份证号、与被继承人关系" },
      { name: "estateList", label: "遗产清单", type: "textarea", required: true, placeholder: "请详细列明全部遗产，如房产、存款、车辆、股权等" },
      { name: "partitionPlan", label: "分割方案", type: "textarea", required: true, placeholder: "请详细说明各项遗产的分配方式及归属" },
      { name: "debtHandling", label: "债务处理", type: "textarea", required: false, placeholder: "选填，如：被继承人债务由XX承担" },
      { name: "otherTerms", label: "其他约定", type: "textarea", required: false, placeholder: "选填" },
    ],
  },
  {
    id: "guardianship-agreement",
    name: "监护协议/指定监护人声明",
    category: "family",
    categoryLabel: "身份/家事类",
    description: "指定或协商确定被监护人的监护人及责任",
    icon: Heart,
    fields: [
      { name: "wardName", label: "被监护人姓名", type: "text", required: true, placeholder: "请输入被监护人姓名" },
      { name: "wardIdNumber", label: "被监护人身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "wardSituation", label: "被监护人情况", type: "select", required: true, placeholder: "", options: ["未成年人", "无民事行为能力人", "限制民事行为能力人"] },
      ...partyFields("guardian", "监护人"),
      { name: "guardianRelationship", label: "与被监护人关系", type: "select", required: true, placeholder: "", options: ["父母", "祖父母/外祖父母", "兄姐", "其他近亲属", "其他"] },
      { name: "guardianshipScope", label: "监护职责范围", type: "textarea", required: true, placeholder: "请说明监护职责，如人身照顾、财产管理、教育医疗决定等" },
      { name: "guardianshipTerm", label: "监护期限", type: "text", required: false, placeholder: "选填，如：至被监护人年满18周岁" },
      { name: "financialArrangement", label: "费用安排", type: "textarea", required: false, placeholder: "选填，如：被监护人财产用于其生活、教育、医疗等" },
    ],
  },
  {
    id: "shareholder-resolution",
    name: "股东会决议/董事会决议",
    category: "corporate",
    categoryLabel: "商事/公司治理类",
    description: "记录股东会或董事会决议事项的正式文书",
    icon: Building2,
    fields: [
      { name: "companyName", label: "公司名称", type: "text", required: true, placeholder: "请输入公司全称" },
      { name: "creditCode", label: "统一社会信用代码", type: "text", required: false, placeholder: "选填" },
      { name: "meetingType", label: "会议类型", type: "select", required: true, placeholder: "", options: ["股东会决议", "董事会决议"] },
      { name: "meetingDate", label: "会议日期", type: "text", required: true, placeholder: "如：2024年6月1日" },
      { name: "meetingPlace", label: "会议地点", type: "text", required: false, placeholder: "选填" },
      { name: "attendees", label: "出席人员", type: "textarea", required: true, placeholder: "请列明全体出席股东/董事及其持股比例或职务" },
      { name: "resolutions", label: "决议事项", type: "textarea", required: true, placeholder: "请逐条列明决议内容，如：1. 同意变更法定代表人为XXX；2. 同意修改公司章程第X条..." },
      { name: "votingResult", label: "表决结果", type: "textarea", required: true, placeholder: "如：全体股东一致同意/经代表XX%表决权的股东同意通过" },
    ],
  },
  {
    id: "legal-rep-change",
    name: "法定代表人变更文件",
    category: "corporate",
    categoryLabel: "商事/公司治理类",
    description: "法定代表人变更的决议及申请文件",
    icon: Briefcase,
    fields: [
      { name: "companyName", label: "公司名称", type: "text", required: true, placeholder: "请输入公司全称" },
      { name: "creditCode", label: "统一社会信用代码", type: "text", required: false, placeholder: "选填" },
      { name: "originalRep", label: "原法定代表人姓名", type: "text", required: true, placeholder: "请输入原法定代表人姓名" },
      { name: "originalRepId", label: "原法定代表人身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "newRep", label: "新法定代表人姓名", type: "text", required: true, placeholder: "请输入新法定代表人姓名" },
      { name: "newRepId", label: "新法定代表人身份证号", type: "text", required: false, placeholder: "选填" },
      { name: "changeReason", label: "变更原因", type: "textarea", required: true, placeholder: "如：原法定代表人因个人原因辞去职务" },
      { name: "changeDate", label: "变更日期", type: "text", required: true, placeholder: "如：2024年6月1日" },
      { name: "registrationAuthority", label: "登记机关", type: "text", required: false, placeholder: "选填，如：北京市朝阳区市场监督管理局" },
    ],
  },
  {
    id: "company-articles",
    name: "公司章程（简版）",
    category: "corporate",
    categoryLabel: "商事/公司治理类",
    description: "有限责任公司章程简版模板",
    icon: BookOpen,
    fields: [
      { name: "companyName", label: "公司名称", type: "text", required: true, placeholder: "请输入公司全称" },
      { name: "registeredAddress", label: "注册地址", type: "text", required: true, placeholder: "请输入公司注册地址" },
      { name: "businessScope", label: "经营范围", type: "textarea", required: true, placeholder: "请描述主要经营范围" },
      { name: "registeredCapital", label: "注册资本（万元）", type: "text", required: true, placeholder: "如：100" },
      { name: "shareholders", label: "股东及出资信息", type: "textarea", required: true, placeholder: "请列明各股东姓名/名称、出资额、出资比例、出资方式、出资时间" },
      { name: "legalRep", label: "法定代表人", type: "text", required: true, placeholder: "请输入法定代表人姓名" },
      { name: "executiveDirector", label: "执行董事/董事会", type: "select", required: true, placeholder: "", options: ["设执行董事（不设董事会）", "设董事会"] },
      { name: "supervisor", label: "监事/监事会", type: "select", required: true, placeholder: "", options: ["设监事一名（不设监事会）", "设监事会"] },
      { name: "profitDistribution", label: "利润分配方式", type: "select", required: true, placeholder: "", options: ["按出资比例分配", "按章程约定比例分配"] },
    ],
  },
  {
    id: "equity-holding-agreement",
    name: "股权代持协议",
    category: "corporate",
    categoryLabel: "商事/公司治理类",
    description: "明确实际出资人与名义股东的权利义务（含风险提示）",
    icon: Users,
    fields: [
      ...partyFields("actualHolder", "实际出资人(甲方)"),
      ...partyFields("nominalHolder", "名义股东(乙方)"),
      { name: "targetCompany", label: "目标公司名称", type: "text", required: true, placeholder: "请输入被代持股权的公司全称" },
      { name: "equityAmount", label: "代持股权比例/金额", type: "text", required: true, placeholder: "如：30%股权，对应出资额30万元" },
      { name: "investmentAmount", label: "实际出资金额（元）", type: "text", required: true, placeholder: "如：300000" },
      { name: "rightsExercise", label: "股东权利行使方式", type: "textarea", required: true, placeholder: "请说明表决权、分红权等如何行使，如：乙方须按甲方书面指示行使表决权" },
      { name: "profitDistribution", label: "收益分配约定", type: "textarea", required: true, placeholder: "如：乙方收到分红后X日内全额转付甲方" },
      { name: "transferRestriction", label: "股权处分限制", type: "textarea", required: true, placeholder: "如：未经甲方书面同意，乙方不得转让、质押或以其他方式处分代持股权" },
      { name: "breachClause", label: "违约责任", type: "textarea", required: true, placeholder: "请约定违约金或赔偿方式" },
      { name: "riskWarning", label: "风险提示事项", type: "textarea", required: false, placeholder: "选填，如：代持协议不得对抗善意第三人；名义股东被执行时的风险等" },
    ],
  },
  {
    id: "partnership-agreement",
    name: "合伙协议",
    category: "corporate",
    categoryLabel: "商事/公司治理类",
    description: "合伙企业或项目合伙的权利义务约定",
    icon: Handshake,
    fields: [
      { name: "partnershipName", label: "合伙企业/项目名称", type: "text", required: true, placeholder: "请输入合伙企业或项目名称" },
      { name: "partnershipType", label: "合伙类型", type: "select", required: true, placeholder: "", options: ["普通合伙", "有限合伙", "项目合伙（非企业）"] },
      { name: "partners", label: "全体合伙人信息", type: "textarea", required: true, placeholder: "请列明各合伙人姓名/名称、身份证号/信用代码、出资额、出资方式" },
      { name: "totalCapital", label: "出资总额（元）", type: "text", required: true, placeholder: "如：500000" },
      { name: "businessScope", label: "经营范围/合伙事务", type: "textarea", required: true, placeholder: "请描述合伙经营的业务范围或项目内容" },
      { name: "profitSharing", label: "利润分配与亏损分担", type: "textarea", required: true, placeholder: "请说明利润分配比例及亏损承担方式" },
      { name: "executingPartner", label: "执行事务合伙人", type: "text", required: true, placeholder: "请指定执行事务的合伙人姓名" },
      { name: "decisionMaking", label: "决策机制", type: "textarea", required: false, placeholder: "选填，如：重大事项须全体合伙人一致同意" },
      { name: "withdrawalTerms", label: "入伙与退伙条款", type: "textarea", required: false, placeholder: "选填，如：退伙需提前30日书面通知" },
      { name: "dissolution", label: "解散与清算", type: "textarea", required: false, placeholder: "选填，如：合伙期满或全体合伙人一致同意解散" },
      { name: "disputeResolution", label: "争议解决方式", type: "select", required: true, placeholder: "", options: ["协商解决，协商不成向合伙企业所在地人民法院起诉", "提交仲裁委员会仲裁"] },
    ],
  },
];

export const categories = [
  { id: "litigation" as DocumentCategory, label: "诉讼类", description: "起诉状、答辩状、上诉状等" },
  { id: "contract" as DocumentCategory, label: "合同类", description: "借款、租赁、买卖等合同" },
  { id: "family" as DocumentCategory, label: "身份/家事类", description: "离婚协议、遗嘱等" },
  { id: "corporate" as DocumentCategory, label: "商事/公司治理类", description: "股东会决议、章程、合伙协议等" },
];
